config/routes.rb
Ear::Application.routes.draw do
  
  resources :images
  resources :net_blocks
  resources :findings
  resources :web_apps
  resources :web_forms
  resources :net_svcs
  resources :physical_locations
  resources :search_strings
  resources :domains
  resources :hosts
  resources :users
  resources :organizations
  resources :tasks
  resources :task_runs 
  resources :object_mappings

  match "/" => "objects#index"
  
  match "/maps" => "maps#index"
  match "/maps/google_default"

  post "task_runner/run"
  get "task_runner/view"

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :organization
  has_many   :hosts
  has_many   :netblocks
  has_many   :task_runs
  
  validates_uniqueness_of :name
  validates_presence_of   :name

  after_save :log
  
  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/finding.rb
class Finding < ActiveRecord::Base
  has_many     :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many     :net_svcs
  has_many     :domains
  has_many     :physical_locations
  has_many     :task_runs
  
  validates_uniqueness_of :ip_address
  validates_presence_of   :ip_address

  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.ip_address}"
  end

private

  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many     :task_runs
  has_many     :physical_locations
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.remote_path}:#{self.local_path}"
  end

  def filename
    self.local_path.split(File::SEPARATOR).last
  end

private

  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/net_block.rb
class NetBlock < ActiveRecord::Base
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.range}"
  end

private

  def log
    EarLogger.instance.log self.to_s
  end
  
end

app/models/net_svc.rb
class NetSvc < ActiveRecord::Base
  belongs_to  :host
  has_many    :web_apps
  has_many    :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{proto}/#{port_num} #{fingerprint}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/object_mapping.rb
class ObjectMapping < ActiveRecord::Base
#    has_one :task_run

    def get_child
      EarLogger.instance.log "Trying to find #{child_type}:#{child_id}"
      
      begin
        eval "#{child_type}.find #{child_id}"
      rescue ActiveRecord::RecordNotFound => e
        EarLogger.instance.log "Oops, couldn't find #{child_type}:#{child_id}"
        nil
      end
      
    end
    
    def get_parent
      EarLogger.instance.log "Trying to find #{parent_type}:#{parent_id}"
      
      begin
        eval "#{parent_type}.find #{parent_id}"
      rescue ActiveRecord::RecordNotFound => e
        EarLogger.instance.log "Oops, couldn't find #{child_type}:#{child_id}"
        nil
      end
    
    end

    def get_task_run
      TaskRun.find self.task_run_id
    end

    def to_s
      "#{self.class}: #{child_type}:#{child_id} <-> #{parent_type}:#{parent_id}"
    end 

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many    :domains
  has_many    :users
  has_many    :physical_locations
  has_many    :hosts, :through => :domains
  has_many    :net_svcs, :through => :hosts
  has_many    :web_apps, :through => :net_svcs
  has_many    :web_forms, :through => :web_apps
  has_many    :task_runs
  
  validates_uniqueness_of :name
  validates_presence_of :name

  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/search_string.rb
class SearchString < ActiveRecord::Base
  has_many     :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/task_run.rb
class TaskRun < ActiveRecord::Base
  belongs_to :organization
  belongs_to :user
  belongs_to :physical_address
  belongs_to :domain
  belongs_to :host
  belongs_to :net_svc
  belongs_to :web_app
  belongs_to :web_form

  def to_s
    "#{name} task -> #{task_object_type}:#{task_object_id} with options #{task_options_hash}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to  :organization
  has_many    :physical_locations
  has_many    :task_runs
  
  
  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.last_name}, #{self.first_name} (#{self.username})"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
  
end

app/models/web_app.rb
class WebApp < ActiveRecord::Base
  belongs_to :net_svc
  has_many    :web_forms
  has_many    :task_runs

  after_save :log
  
  include ModelHelper

  def to_s
    "#{self.class}: #{self.name} -  #{self.url}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/models/web_form.rb
class WebForm < ActiveRecord::Base
  belongs_to :web_app
  has_many    :task_runs

  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name} - #{self.url} -> #{self.action}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/controllers/search_strings_controller.rb
class SearchStringsController < ApplicationController
  # GET /search_strings
  # GET /search_strings.json
  def index
    @search_strings = SearchString.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_strings }
    end
  end

  # GET /search_strings/1
  # GET /search_strings/1.json
  def show
    @search_string = SearchString.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_string }
    end
  end

  # GET /search_strings/new
  # GET /search_strings/new.json
  def new
    @search_string = SearchString.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_string }
    end
  end

  # GET /search_strings/1/edit
  def edit
    @search_string = SearchString.find(params[:id])
  end

  # POST /search_strings
  # POST /search_strings.json
  def create
    @search_string = SearchString.new(params[:search_string])

    respond_to do |format|
      if @search_string.save
        format.html { redirect_to @search_string, notice: 'Search string was successfully created.' }
        format.json { render json: @search_string, status: :created, location: @search_string }
      else
        format.html { render action: "new" }
        format.json { render json: @search_string.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_strings/1
  # PUT /search_strings/1.json
  def update
    @search_string = SearchString.find(params[:id])

    respond_to do |format|
      if @search_string.update_attributes(params[:search_string])
        format.html { redirect_to @search_string, notice: 'Search string was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_string.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_strings/1
  # DELETE /search_strings/1.json
  def destroy
    @search_string = SearchString.find(params[:id])
    @search_string.destroy

    respond_to do |format|
      format.html { redirect_to search_strings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/findings_helper.rb
module FindingsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/net_svcs_helper.rb
module NetSvcsHelper
end

app/helpers/search_strings_helper.rb
module SearchStringsHelper
end

app/helpers/task_runs_helper.rb
module TaskRunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/web_apps_helper.rb
module WebAppsHelper
end

app/views/search_strings/_form.html.erb
<%= form_for(@search_string) do |f| %>
  <% if @search_string.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_string.errors.count, "error") %> prohibited this search_string from being saved:</h2>

      <ul>
      <% @search_string.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_strings/edit.html.erb
<h1>Editing search_string</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_string %> |
<%= link_to 'Back', search_strings_path %>

app/views/search_strings/index.html.erb
<h1>Listing search_strings</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @search_strings.each do |search_string| %>
  <tr>
    <td><%= search_string.name %></td>
    <td><%= link_to 'Show', search_string %></td>
    <td><%= link_to 'Edit', edit_search_string_path(search_string) %></td>
    <td><%= link_to 'Destroy', search_string, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search string', new_search_string_path %>

app/views/search_strings/new.html.erb
<h1>New search_string</h1>

<%= render 'form' %>

<%= link_to 'Back', search_strings_path %>

app/views/search_strings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @search_string.name %>
</p>

<p>
<b>Parents:</b>
  <ul>
  <% @search_string.parents.each {|p|%>
    <li><%= link_to p, eval("#{p.underscore}_path(p)")  %></li>
  <% } %>
  </ul>
</p>  

<p>
<b>Children:</b>
  <ul>
  <% @search_string.children.each {|c|%>
    <li><%= link_to c, eval("#{c.underscore}_path(c)")  %></li>
  <% } %>
  </ul>
</p>

<p>
<b>Tasks:</b>
  <ul>
  <% @search_string.tasks.each {|t|%>
    <li><%= link_to t, eval("#{t.underscore}_path(t.name)")  %></li>
  <% } %>
  </ul>
</p>

<%= link_to 'Edit', edit_search_string_path(@search_string) %> |
<%= link_to 'Back', search_strings_path %>