config/routes.rb
Ear::Application.routes.draw do
  
  resources :images
  resources :net_blocks
  resources :findings
  resources :web_apps
  resources :web_forms
  resources :net_svcs
  resources :physical_locations
  resources :search_strings
  resources :domains
  resources :hosts
  resources :users
  resources :organizations
  resources :tasks
  resources :task_runs 
  resources :object_mappings

  match "/" => "objects#index"
  
  match "/maps" => "maps#index"
  match "/maps/google_default"

  post "task_runner/run"
  get "task_runner/view"

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :organization
  has_many   :hosts
  has_many   :netblocks
  has_many   :task_runs
  
  validates_uniqueness_of :name
  validates_presence_of   :name

  after_save :log
  
  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/finding.rb
class Finding < ActiveRecord::Base
  has_many     :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many     :net_svcs
  has_many     :domains
  has_many     :physical_locations
  has_many     :task_runs
  
  validates_uniqueness_of :ip_address
  validates_presence_of   :ip_address

  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.ip_address}"
  end

private

  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many     :task_runs
  has_many     :physical_locations
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.remote_path}:#{self.local_path}"
  end

  def filename
    self.local_path.split(File::SEPARATOR).last
  end

private

  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/net_block.rb
class NetBlock < ActiveRecord::Base
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.range}"
  end

private

  def log
    EarLogger.instance.log self.to_s
  end
  
end

app/models/net_svc.rb
class NetSvc < ActiveRecord::Base
  belongs_to  :host
  has_many    :web_apps
  has_many    :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{proto}/#{port_num} #{fingerprint}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/object_mapping.rb
class ObjectMapping < ActiveRecord::Base
#    has_one :task_run

    def get_child
      EarLogger.instance.log "Trying to find #{child_type}:#{child_id}"
      
      begin
        eval "#{child_type}.find #{child_id}"
      rescue ActiveRecord::RecordNotFound => e
        EarLogger.instance.log "Oops, couldn't find #{child_type}:#{child_id}"
        nil
      end
      
    end
    
    def get_parent
      EarLogger.instance.log "Trying to find #{parent_type}:#{parent_id}"
      
      begin
        eval "#{parent_type}.find #{parent_id}"
      rescue ActiveRecord::RecordNotFound => e
        EarLogger.instance.log "Oops, couldn't find #{child_type}:#{child_id}"
        nil
      end
    
    end

    def get_task_run
      TaskRun.find self.task_run_id
    end

    def to_s
      "#{self.class}: #{child_type}:#{child_id} <-> #{parent_type}:#{parent_id}"
    end 

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many    :domains
  has_many    :users
  has_many    :physical_locations
  has_many    :hosts, :through => :domains
  has_many    :net_svcs, :through => :hosts
  has_many    :web_apps, :through => :net_svcs
  has_many    :web_forms, :through => :web_apps
  has_many    :task_runs
  
  validates_uniqueness_of :name
  validates_presence_of :name

  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/search_string.rb
class SearchString < ActiveRecord::Base
  has_many     :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/task_run.rb
class TaskRun < ActiveRecord::Base
  belongs_to :organization
  belongs_to :user
  belongs_to :physical_address
  belongs_to :domain
  belongs_to :host
  belongs_to :net_svc
  belongs_to :web_app
  belongs_to :web_form

  def to_s
    "#{name} task -> #{task_object_type}:#{task_object_id} with options #{task_options_hash}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to  :organization
  has_many    :physical_locations
  has_many    :task_runs
  
  
  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.last_name}, #{self.first_name} (#{self.username})"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
  
end

app/models/web_app.rb
class WebApp < ActiveRecord::Base
  belongs_to :net_svc
  has_many    :web_forms
  has_many    :task_runs

  after_save :log
  
  include ModelHelper

  def to_s
    "#{self.class}: #{self.name} -  #{self.url}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/models/web_form.rb
class WebForm < ActiveRecord::Base
  belongs_to :web_app
  has_many    :task_runs

  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name} - #{self.url} -> #{self.action}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/controllers/net_svcs_controller.rb
class NetSvcsController < ApplicationController
  # GET /net_svcs
  # GET /net_svcs.json
  def index
    @net_svcs = NetSvc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @net_svcs }
    end
  end

  # GET /net_svcs/1
  # GET /net_svcs/1.json
  def show
    @net_svc = NetSvc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @net_svc }
    end
  end

  # GET /net_svcs/new
  # GET /net_svcs/new.json
  def new
    @net_svc = NetSvc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @net_svc }
    end
  end

  # GET /net_svcs/1/edit
  def edit
    @net_svc = NetSvc.find(params[:id])
  end

  # POST /net_svcs
  # POST /net_svcs.json
  def create
    @net_svc = NetSvc.new(params[:net_svc])

    respond_to do |format|
      if @net_svc.save
        format.html { redirect_to @net_svc, notice: 'Net svc was successfully created.' }
        format.json { render json: @net_svc, status: :created, location: @net_svc }
      else
        format.html { render action: "new" }
        format.json { render json: @net_svc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /net_svcs/1
  # PUT /net_svcs/1.json
  def update
    @net_svc = NetSvc.find(params[:id])

    respond_to do |format|
      if @net_svc.update_attributes(params[:net_svc])
        format.html { redirect_to @net_svc, notice: 'Net svc was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @net_svc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /net_svcs/1
  # DELETE /net_svcs/1.json
  def destroy
    @net_svc = NetSvc.find(params[:id])
    @net_svc.destroy

    respond_to do |format|
      format.html { redirect_to net_svcs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/findings_helper.rb
module FindingsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/net_svcs_helper.rb
module NetSvcsHelper
end

app/helpers/task_runs_helper.rb
module TaskRunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/web_apps_helper.rb
module WebAppsHelper
end

app/helpers/web_forms_helper.rb
module WebFormsHelper
end

app/views/net_svcs/_form.html.erb
<%= form_for(@net_svc) do |f| %>
  <% if @net_svc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@net_svc.errors.count, "error") %> prohibited this net_svc from being saved:</h2>

      <ul>
      <% @net_svc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fingerprint %><br />
    <%= f.text_field :fingerprint %>
  </div>
  <div class="field">
    <%= f.label :port_num %><br />
    <%= f.number_field :port_num %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/net_svcs/edit.html.erb
<h1>Editing net_svc</h1>

<%= render 'form' %>

<%= link_to 'Show', @net_svc %> |
<%= link_to 'Back', net_svcs_path %>

app/views/net_svcs/index.html.erb
<h1>Listing net_svcs</h1>

<table>
  <tr>
    <th>Host</th>
    <th>Port</th>
    <th>Name</th>
    <th>Fingerprint</>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @net_svcs.each do |net_svc| %>
  <tr>
    <td><%= net_svc.host %></td>
    <td><%= net_svc.port_num %></td>
    <td><%= net_svc.name %></td>
    <td><%= net_svc.fingerprint %></td>
    <td><%= link_to 'Show', net_svc %></td>
    <td><%= link_to 'Edit', edit_net_svc_path(net_svc) %></td>
    <td><%= link_to 'Destroy', net_svc, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Net svc', new_net_svc_path %>

app/views/net_svcs/new.html.erb
<h1>New net_svc</h1>

<%= render 'form' %>

<%= link_to 'Back', net_svcs_path %>

app/views/net_svcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @net_svc.name %>
</p>

<p>
  <b>Fingerprint:</b>
  <%= @net_svc.fingerprint %>
</p>

<p>
  <b>Port:</b>
  <%= @net_svc.port_num %>
</p>

<p>
<b>Parents:</b>
  <ul>
  <% @net_svc.parents.each {|p|%>
    <li><%= link_to p, eval("#{p.underscore}_path(p)")  %></li>
  <% } %>
  </ul>
</p>  

<p>
<b>Children:</b>
  <ul>
  <% @net_svc.children.each {|c|%>
    <li><%= link_to c, eval("#{c.underscore}_path(c)")  %></li>
  <% } %>
  </ul>
</p>

<p>
<b>Tasks:</b>
  <ul>
  <% @net_svc.tasks.each {|t|%>
    <li><%= link_to t, eval("#{t.underscore}_path(t.name)")  %></li>
  <% } %>
  </ul>
</p>


<%= link_to 'Edit', edit_net_svc_path(@net_svc) %> |
<%= link_to 'Back', net_svcs_path %>