config/routes.rb
Ear::Application.routes.draw do
  
  resources :images
  resources :net_blocks
  resources :findings
  resources :web_apps
  resources :web_forms
  resources :net_svcs
  resources :physical_locations
  resources :search_strings
  resources :domains
  resources :hosts
  resources :users
  resources :organizations
  resources :tasks
  resources :task_runs 
  resources :object_mappings

  match "/" => "objects#index"
  
  match "/maps" => "maps#index"
  match "/maps/google_default"

  post "task_runner/run"
  get "task_runner/view"

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :organization
  has_many   :hosts
  has_many   :netblocks
  has_many   :task_runs
  
  validates_uniqueness_of :name
  validates_presence_of   :name

  after_save :log
  
  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/finding.rb
class Finding < ActiveRecord::Base
  has_many     :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many     :net_svcs
  has_many     :domains
  has_many     :physical_locations
  has_many     :task_runs
  
  validates_uniqueness_of :ip_address
  validates_presence_of   :ip_address

  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.ip_address}"
  end

private

  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many     :task_runs
  has_many     :physical_locations
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.remote_path}:#{self.local_path}"
  end

  def filename
    self.local_path.split(File::SEPARATOR).last
  end

private

  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/net_block.rb
class NetBlock < ActiveRecord::Base
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.range}"
  end

private

  def log
    EarLogger.instance.log self.to_s
  end
  
end

app/models/net_svc.rb
class NetSvc < ActiveRecord::Base
  belongs_to  :host
  has_many    :web_apps
  has_many    :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{proto}/#{port_num} #{fingerprint}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/object_mapping.rb
class ObjectMapping < ActiveRecord::Base
#    has_one :task_run

    def get_child
      EarLogger.instance.log "Trying to find #{child_type}:#{child_id}"
      
      begin
        eval "#{child_type}.find #{child_id}"
      rescue ActiveRecord::RecordNotFound => e
        EarLogger.instance.log "Oops, couldn't find #{child_type}:#{child_id}"
        nil
      end
      
    end
    
    def get_parent
      EarLogger.instance.log "Trying to find #{parent_type}:#{parent_id}"
      
      begin
        eval "#{parent_type}.find #{parent_id}"
      rescue ActiveRecord::RecordNotFound => e
        EarLogger.instance.log "Oops, couldn't find #{child_type}:#{child_id}"
        nil
      end
    
    end

    def get_task_run
      TaskRun.find self.task_run_id
    end

    def to_s
      "#{self.class}: #{child_type}:#{child_id} <-> #{parent_type}:#{parent_id}"
    end 

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many    :domains
  has_many    :users
  has_many    :physical_locations
  has_many    :hosts, :through => :domains
  has_many    :net_svcs, :through => :hosts
  has_many    :web_apps, :through => :net_svcs
  has_many    :web_forms, :through => :web_apps
  has_many    :task_runs
  
  validates_uniqueness_of :name
  validates_presence_of :name

  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/search_string.rb
class SearchString < ActiveRecord::Base
  has_many     :task_runs
  
  after_save   :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end

end

app/models/task_run.rb
class TaskRun < ActiveRecord::Base
  belongs_to :organization
  belongs_to :user
  belongs_to :physical_address
  belongs_to :domain
  belongs_to :host
  belongs_to :net_svc
  belongs_to :web_app
  belongs_to :web_form

  def to_s
    "#{name} task -> #{task_object_type}:#{task_object_id} with options #{task_options_hash}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to  :organization
  has_many    :physical_locations
  has_many    :task_runs
  
  
  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.last_name}, #{self.first_name} (#{self.username})"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
  
end

app/models/web_app.rb
class WebApp < ActiveRecord::Base
  belongs_to :net_svc
  has_many    :web_forms
  has_many    :task_runs

  after_save :log
  
  include ModelHelper

  def to_s
    "#{self.class}: #{self.name} -  #{self.url}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/models/web_form.rb
class WebForm < ActiveRecord::Base
  belongs_to :web_app
  has_many    :task_runs

  after_save :log

  include ModelHelper

  def to_s
    "#{self.class}: #{self.name} - #{self.url} -> #{self.action}"
  end

private
  def log
    EarLogger.instance.log self.to_s
  end
end

app/controllers/object_mappings_controller.rb
class ObjectMappingsController < ApplicationController
  # GET /object_mappings
  # GET /object_mappings.json
  def index
    @object_mappings = ObjectMapping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @object_mappings }
    end
  end

  # GET /object_mappings/1
  # GET /object_mappings/1.json
  def show
    @object_mapping = ObjectMapping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @object_mapping }
    end
  end

  # GET /object_mappings/new
  # GET /object_mappings/new.json
  def new
    @object_mapping = ObjectMapping.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @object_mapping }
    end
  end

  # GET /object_mappings/1/edit
  def edit
    @object_mapping = ObjectMapping.find(params[:id])
  end

  # POST /object_mappings
  # POST /object_mappings.json
  def create
    @object_mapping = ObjectMapping.new(params[:object_mapping])

    respond_to do |format|
      if @object_mapping.save
        format.html { redirect_to @object_mapping, notice: 'Object mapping was successfully created.' }
        format.json { render json: @object_mapping, status: :created, location: @object_mapping }
      else
        format.html { render action: "new" }
        format.json { render json: @object_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /object_mappings/1
  # PUT /object_mappings/1.json
  def update
    @object_mapping = ObjectMapping.find(params[:id])

    respond_to do |format|
      if @object_mapping.update_attributes(params[:object_mapping])
        format.html { redirect_to @object_mapping, notice: 'Object mapping was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @object_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /object_mappings/1
  # DELETE /object_mappings/1.json
  def destroy
    @object_mapping = ObjectMapping.find(params[:id])
    @object_mapping.destroy

    respond_to do |format|
      format.html { redirect_to object_mappings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/findings_helper.rb
module FindingsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/net_svcs_helper.rb
module NetSvcsHelper
end

app/helpers/object_mappings_helper.rb
module ObjectMappingsHelper
end

app/helpers/task_runs_helper.rb
module TaskRunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/web_apps_helper.rb
module WebAppsHelper
end

app/views/object_mappings/_form.html.erb
<%= form_for(@object_mapping) do |f| %>
  <% if @object_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@object_mapping.errors.count, "error") %> prohibited this object_mapping from being saved:</h2>

      <ul>
      <% @object_mapping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.number_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :child_type %><br />
    <%= f.text_field :child_type %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :parent_type %><br />
    <%= f.text_field :parent_type %>
  </div>
  <div class="field">
    <%= f.label :task_run_id %><br />
    <%= f.number_field :task_run_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/object_mappings/edit.html.erb
<h1>Editing object_mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @object_mapping %> |
<%= link_to 'Back', object_mappings_path %>

app/views/object_mappings/index.html.erb
<h1>Listing object_mappings</h1>

<table>
  <tr>
    <th>Child</th>
    <th>Child type</th>
    <th>Parent</th>
    <th>Parent type</th>
    <th>Task run</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @object_mappings.each do |object_mapping| %>
  <tr>
    <td><%= object_mapping.child_id %></td>
    <td><%= object_mapping.child_type %></td>
    <td><%= object_mapping.parent_id %></td>
    <td><%= object_mapping.parent_type %></td>
    <td><%= object_mapping.task_run_id %></td>
    <td><%= link_to 'Show', object_mapping %></td>
    <td><%= link_to 'Edit', edit_object_mapping_path(object_mapping) %></td>
    <td><%= link_to 'Destroy', object_mapping, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Object mapping', new_object_mapping_path %>

app/views/object_mappings/new.html.erb
<h1>New object_mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', object_mappings_path %>

app/views/object_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Child:</b>
  <%= @object_mapping.child_id %>
</p>

<p>
  <b>Child type:</b>
  <%= @object_mapping.child_type %>
</p>

<p>
  <b>Parent:</b>
  <%= @object_mapping.parent_id %>
</p>

<p>
  <b>Parent type:</b>
  <%= @object_mapping.parent_type %>
</p>

<p>
  <b>Task run:</b>
  <%= @object_mapping.task_run_id %>
</p>


<%= link_to 'Edit', edit_object_mapping_path(@object_mapping) %> |
<%= link_to 'Back', object_mappings_path %>